server:
  port: 8082
  compression:
    enabled: true
    mime-types: application/json

spring:
  application:
    name: user-service
  profiles:
    active: @spring.profiles.active@

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO