spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/room_db
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: false
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    show-sql: false
    hibernate:
      ddl-auto: update
#  sendGrid:
#    apiKey: ${SENDGRID_API_KEY:DUMMY-SENDGRID-API-KEY}
#    fromEmail: ${SENDGRID_FROM_EMAIL:quoctay87@gmail.com}
#    templateId: ${SENDGRID_TEMPLATE_ID:d-2116466afd0a438b90615184dd569e42}
#    verificationLink: ${SENDGRID_VERIFICATION_LINK:http://localhost:8080/user/confirm-email}

# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: ${BACKEND_HOST:http://localhost:${server.port}}
    title: User Service
    version: 1.0.0